apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Q3Rxjt9+nlkkc40fcG6erdMOnjOB6okhR5Zuq+4EyW5LMtEPaLp8ZCKXDAIlNcVGp2bwTqLSEoHRW/LQLqTa2w3gDnXdcEeD19iHDTyFjeP0Dy8ZfB6mWQeeutq+0bHjnzRTzf++dSRWWPjjZu+U0Qtmq62A8yaWut2o3u6CHy4/fdeVecGTSwRlE/PDaNeJUZ/UaGnHEP2IgKUvCaLoSV5HxmUkGGQaoSDhx0HKIlrWc4bQ2KYisBrusQ64A1JTc5Svg7+eUVcnO9tBG0PEfuPUXSR+z9k5r1+PSvEzK5+pf1NgrgrM1Pap1ftQUGREZJDlKkKjm/ZmY600TGl81+YVRYRbmcX4GwaYc4IZozfRoCt4KeOha+P57GHOMUjw,iv:4xSomgVaDRTmRbGKMxLZ/oXdWAC5d/BITJ+pewlLXSM=,tag:Hwq/V5+fKaCXajD/YIDDwQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:bfnSHxMLANK1pI2DYqHs4UZbx+s6sufovWTL7zJjVbtPlgoYXn0cPk1JLCVz37BsxQIbBDBjHDdoUZd/M2y5mSZMxo8vm94WfRE2U31zYt/ka+yKAxEe9inF2ZZRlqlCN/5KmFuPUfE9twSbpbz213x9FQ75Hq3G+1hedXvmMs5pOcRnCX0lgyhg8Npm3C/mARnu9Q8lZBCRAGG9K7tHMXuKbXzlblIilIDWTB4aSYznPPWPfdQv5Kk664GpW5ujX1jUYEqRjWM0Xxy3Dg==,iv:cEtxIx0of9Idn0FAbCqti9kFACuIULxfvm/kU1X5z70=,tag:F/72M9N3dLW9RnQW5+5tmA==,type:str]
    known_hosts: ENC[AES256_GCM,data:uGJz/4eJGXu8M3ygdA4tqFjJ/s8DcWvNaAea973WjLgaavfJ5oFtqs8FWBQym+OVWxy4fsGnvGLRy1yXJkGIuhTexxXKFUFnY2c01WAa7fWgZ+YOFdXxP1/KiYq/9dtKloIpqWYc1FadSNQOtYideoUmvYs7DvqD1UuKLiDZGLRm381ya6xbyV5IcIXkepZnJ1C4YEJwWfWWSSx/7+P4YkwMWmunmCCzrawh,iv:NpoQlOkI2zCulDgpFZkWtnewn5xm+5IG5ymHUcWED/o=,tag:e+bZ+YArcVubPF2Fuz9Xpw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age16umlumgdfgazwgplt44pgn8lfqm2u7khlpdz5elsjvcsnme57d0q6rfkn3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TzlMVVRoTGNGeSs5MnhU
            dkJ6UnYxYkRnOXVGbURmQWZySEd4R0QvZlZZCk5IOWM4bEhDbTc2R2I0NlVaUEp0
            aUZ4cVlFQzdXRnVoOGx5eTkyQWlJWkEKLS0tIDZtWVJxUXpGbmgwd0tIblhtZEx1
            elhHdzFaQ2VNTVVwa3djVjVSUFZBRlEKTwlM/AaS+MlFwc+pQUONKMruSMlQjyY9
            yQ4Hdh0j2yKufpFDMkbKNBG7syXSn+1sFSr+n5aHX5aqSasw2f+4PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T15:14:32Z"
    mac: ENC[AES256_GCM,data:w+e0qqjOetQp2Y9159Ob4wn8MN8S8HRh/Pw5h7pbub9oMX2xr0u2wuEZeLv+EfUoI62eH0vF5xn6Ts746K/5hcMTZMngn6f8Tk7mF3fzuQOjPfFfTRpeY/c4NViux25xEfiRiOFSgM5VfjgHYLbgw78/UEu10Ei4h1LWxeNZpOg=,iv:aAhq2dSVIARa46J4M8aPpZYHf8xG0JFGjQO90uK2uzM=,tag:cQpn3SnC37CMO1VmBSfIAg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
